services:
  raimu:
    container_name: "raimu"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - "./volumes/deepface:/root/.deepface"
      - "./volumes/keras:/root/.keras"
    restart: always