#FROM python:3.11-slim
FROM tensorflow/tensorflow:2.15.0-gpu

# Update pip
RUN pip install --upgrade pip

# Install HDF5 using apt
RUN apt-get update && apt-get install -y pkg-config gcc libhdf5-dev cuda-toolkit-12-3

# For deepface
RUN apt-get install ffmpeg libsm6 libxext6 libgl1 -y

WORKDIR /src

# Install h5py with no-binary flag
RUN pip install --no-binary h5py h5py

COPY ./requirements.txt /src/requirements.txt

# RUN pip install --no-cache-dir --upgrade -r /src/requirements.txt
RUN pip install --no-cache-dir --upgrade --ignore-installed blinker -r /src/requirements.txt

COPY ./app /src/app

EXPOSE 80

# CMD ["fastapi", "run", "app/main.py", "--port", "80"]
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
