FROM tensorflow/tensorflow:2.15.0-gpu

# Update pip
RUN pip install --upgrade pip

# Install dependencies via apt
RUN apt-get update && apt-get install -y \
    pkg-config \
    gcc \
    libhdf5-dev \
    ffmpeg \
    libsm6 \
    libxext6 \
    libgl1 \
    cuda-toolkit-12-3 \
 && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /src

# Install h5py with no-binary flag
RUN pip install --no-binary=h5py h5py

# Copy and install Python dependencies, excluding TensorFlow
COPY ./requirements.txt /src/requirements.txt
RUN grep -vE "^(tensorflow|tensorflow-cpu|tensorflow-gpu)" /src/requirements.txt > /src/requirements-nogpu.txt \
 && pip install --no-cache-dir --upgrade --ignore-installed blinker -r /src/requirements-nogpu.txt

COPY ./app /src/app

EXPOSE 80

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
